argus:
  podSecurityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
  securityContext:
    readOnlyRootFilesystem: false
  persistence:
    config:
      objectName: pav-argus-config
      mountPath: /config
  command:
  - "/bin/sh"
  - "-c"
  - "cp /config/config.yml /etc/argus/config.yml && /bin/argus -config.file=/etc/argus/config.yml"
  # lifecycle:
  #   postStart:
  #     exec:
  #       command: ["/bin/sh", "-c", "cp /config/config.yml /etc/argus/config.yml"]

  config:
    service:
      dani-garcia/vaultwarden:
        type: github
        url: dani-garcia/vaultwarden
        web_url: https://github.com/dani-garcia/vaultwarden/releases/{{ version }}
        icon: https://raw.githubusercontent.com/dani-garcia/vaultwarden/main/src/static/images/vaultwarden-icon.png
        deployed_version:
          url: http://pav:5000/versions/vaultwarden
          regex: ([0-9.]+)

      louislam/uptime-kuma:
        type: github
        url: louislam/uptime-kuma
        web_url: https://github.com/louislam/uptime-kuma/releases/{{ version }}
        icon: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.png
        deployed_version:
          url: http://pav:5000/versions/uptimekuma
          regex: ([0-9.]+)

apps:
  vaultwarden: 1.0.0
  uptimekuma: 0.11.0

extensions:
  argus: true